### ISSUE TITLE
IE 11 bug

### ISSUE THREAD

**Issue by panay** [KazanExpress/vue-simple-suggest#90] opened 2018-10-05 08:49 UTC
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
I use it in IE11 and get the error: `Syntax error`: `...const a=t=>t.some(t=>t===e.keyCode)`.
I discovered it and found that this piece of code is in `https://github.com/KazanExpress/vue-simple-suggest/blob/master/lib/misc.js` and babel-loader cannot transpile it into ES5.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- import this plugin as CJS: vue-simple-suggest/dist/cjs
- use it on some page
- open this page in IE11
- get syntax error

## **What is the expected behavior?**
I expect that this plugin will be work correct in IE11

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [x] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [x] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.9.3
  - Vue-simple-suggest version: 1.8.2
  - Browser: [all]
  - Language: [ES6/7 | ES5]

**Comment by Raiondesu** [comment] 2018-10-05 10:38
Hello, @panay.
From your report we see that you do not import vue-simple-suggest's cjs build, since cjs build is self-sustained and [does not contain such code](https://github.com/KazanExpress/vue-simple-suggest/blob/master/dist/cjs.js).

Whatever you found in `misc.js` does not go to the cjs build untranspiled, so you either imported the wrong build somewhere or wrote this code yourself. No other variations are possible.//

Duplicate of #75.

**Closed by Raiondesu** 2018-10-05 10:38 UTC
Labels: duplicate, invalid, wontfix
