### ISSUE TITLE
Clear input after click in @select bugs

### ISSUE THREAD

**Issue by jakubstankowski** [KazanExpress/vue-simple-suggest#183] opened 2019-10-07 13:17 UTC
Hi! Thanks for help me in my previous issue...

## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## **What is the current behavior?**
Similar bugs - https://github.com/KazanExpress/vue-simple-suggest/issues/71

After select something in autosuggest list, i would like reset input, i try two solutions, one from that 71 issue, but it's not working.

Could you clone this repo ? 
https://github.com/jakubstankowski/simple-autosuggest-bug/blob/master/Query-Builder.vue

## **What is the expected behavior?**
After click something in suggest list, input v-model value, **should be empty** 

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [x] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

Thanks for help my!

**Comment by Raiondesu** [comment] 2019-10-07 13:26
Hello, @jakubstankowski. :)

Unfortunately, you didn't get the whole picture in #71.

The complete solution would be along the following lines:

```js
onSuggestSelect(value) {
  this.selectValue = value.login;
  this.chosen = '';

  this.$nextTick(() => {
    this.$refs.suggestComponent.$el.querySelector('input').blur()
    this.$refs.suggestComponent.setText('');
  });
}
```

See `setText` in [ref methods](https://github.com/KazanExpress/vue-simple-suggest#ref-methods). Good luck.

I'm closing the issue, as this is not a bug with the component itself.

P.S. Thanks for the reproduction repo, btw. :)

**Closed by Raiondesu** 2019-10-07 13:26 UTC

**Comment by 1c7** [comment] 2021-12-22 09:19
`this.$nextTick(() => {` Works for me   
(`vue-simple-suggest` version `1.11.2`)   
Thanks!
