### ISSUE TITLE
Focus event seems not to be registering in Safari or Firefox

### ISSUE THREAD

**Issue by elketal** [KazanExpress/vue-simple-suggest#74] opened 2018-07-13 16:42 UTC
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**
Background:
I'm using several simple-suggest components in one form. The first is a list of shipper names, the second a list of addresses. The second's list is generated based on the input from the first. 

When the second input comes into focus, it's supposed to trigger a function that sends a POST request to get back a list of locations based on the name selected in the previous input. Unfortunately, the expected behavior is only happening in Chrome. 

I initially tried to use v-on:select="function" on the first input, but found that it was only sending what the user had typed, not the actual selection; so I decided to make it @focus="function" on the second, ensuring that the selection registered prior to the request being sent. 

This works like a charm in Chrome, but nothing happens in Safari or Firefox (although the "focus" class is appearing on the div)-- it appears that the browser doesn't register a focus event being emitted. A similar function works on a regular <textarea> in all browsers, so it seems it's vue-simple-suggest causing the problem.  

I have no idea how to go about fixing this, or figuring out why it's happening.

## **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Here's a demo that shows the issue (I've removed the API calls and the rest of the interface for security/eas of use purposes):
https://codesandbox.io/s/k5y9pnm3v

## **What is the expected behavior?**

When the second input comes into focus, it's supposed to trigger a function that sends a POST request to get back a list of locations based on the name selected in the previous input. 

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser:  Firefox 59.0.2 | Safari 11.1.1 ]
  - Language: [ ES6/7 | ES5 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by elketal** [comment] 2018-07-16 16:36
For the record, it doesn't work on Safari mobile either.

**Comment by kaskar2008** [comment] 2018-07-17 13:17
@elketal Thank you for your report.
I literally have no idea right now how to resolve this problem. I'll try find a solution in the next week.
@Raiondesu, I need help.

**Comment by elketal** [comment] 2018-07-17 14:22
Haha that makes me feel a little better about not being able to figure it out! Thank you for your attention to the issue!

**Comment by elketal** [comment] 2018-07-17 17:39
While trying to do something else, I've discovered that the input event fires before the actual input has registered with the component. So if I do console.log(this.value) on input it logs the previous value, not the value that I've just typed. Dunno if that has something to do with it, but I thought I'd let you know.

**Comment by Raiondesu** [comment] 2018-08-06 10:44
@elketal, I'll be looking into the problem this week.
I have a couple of thoughts regarding the possible solution.
Currently, the "focus" event relies on a mix of browser native and custom js logic. This might be the root cause of the problem, if FireFox implements the native focus event differently from other browsers (which it most probably does).

**Comment by mila76** [comment] 2018-08-19 20:55
I see this bug too... is a little annoyng... 
If you use keyboard to select all go smooth, only if click on mouse the problem occur

The problem is related on the focus of the input... with keyboard you never leave the input so all go as expected
When you click on the list the input loose the focus but (i think  your login) leave the .focus class
In firefox input never regain focus (in chrome yes, you can see the blink on input) so you have to click in input by yourself and than all go as expected....

I try to understand why the input dont regain focus after click on list

**Comment by Raiondesu** [comment] 2018-08-20 14:27
@mila76, component actually works exactly the way you described.
I think, though, that in some firefox versions the event firing order is a little different from the "mainstream".

**Comment by mila76** [comment] 2018-08-20 14:41
I haven't see the "focus" code on the component (maybe i missed)

I tested: 
Edge (last) and work like chrome
Firefox 52.9.0 ESR and 61.0.2 both have the bug :(

**Comment by kaskar2008** [comment] 2018-08-20 14:45
@elketal, I noticed something in your [example](https://codesandbox.io/s/k5y9pnm3v). Did you try setting the [`min-length`](https://github.com/KazanExpress/vue-simple-suggest#props) prop to 0?
The example works just fine after I added the prescribed prop.

**Comment by mila76** [comment] 2018-08-20 14:54
if fixed this issue adding the `this.inputElement.focus()` on suggestionClick function

**Comment by mila76** [comment] 2018-08-21 10:03
@elketal why dont put the Ajax call on @select of the first? I usually do this for that kind of functionality... 

For the record for me the problem in only secondary, related on the graphics (focus class remain), i'm not sure if my fix is good for @elketal situation 
(sorry for my misunderstanding)

**Comment by Raiondesu** [comment] 2018-08-22 10:34
@mila76, it seems to me that your problem is a bit different from the topic.

@elketal, I'm going to close this issue for maintaining purposes. If the problem persists - feel free to write here.

**Closed by Raiondesu** 2018-08-22 10:34 UTC
Labels: bug, good first issue, refactoring

**Comment by Raiondesu** [comment] 2018-08-22 14:52
Seems to be connected to #81 though.
