### ISSUE TITLE
How hide suggest list?

### ISSUE THREAD

**Issue by Sendoo** [KazanExpress/vue-simple-suggest#214] opened 2019-11-07 17:29 UTC
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## **What is the current behavior?**
How hide suggest list after select in mode="select"?
After select, autofocus occurs on the input field and suggest list appears again.

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [x] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  
  - Vue.js Version: 2.5.0
  - Vue-simple-suggest version: 1.7.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kaskar2008** [comment] 2019-11-08 07:56
Duplicate of the #203

**Closed by kaskar2008** 2019-11-08 07:56 UTC
Labels: bug, duplicate
