### ISSUE TITLE
Reset input after validation

### ISSUE THREAD

**Issue by Geminii** [KazanExpress/vue-simple-suggest#71] opened 2018-06-26 14:30 UTC
Hi everybody,

## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

## ** Configuration **
```
<vue-simple-suggest ref="suggestComponent"
                          v-model="selected" mode="select"
                          :max-suggestions="10"
                          :min-length="1"
                          :debounce="200"
                          :controls="{
                            selectionUp: [38, 33],
                            selectionDown: [40, 34],
                            select: [13, 36],
                            hideList: [27, 35]
                          }"
                          :list="simpleSuggestionList"
                          :placeholder="placeholder"
                          :display-attribute="'value'"
                          :value-attribute="'value'"
                          @select="validAutocomplete"
                          @hover="onSuggestHover"
                          @request-start="onRequestStart"
                          @request-done="onRequestDone">
        <input class="inputText" v-model="text" :display-attribute="'count'" />
        ....
</vue-simple-suggest>
```

## **What is the current behavior?**
**I'm using the `select` mode with a min-length at 1.** 
When i select an item (mouse or keyboard) then validate the input, **i need to reset the input and blur.**  How can i do this ? 

I try to reset the v-model text like this into `validAutocomplete` method.
```
validAutocomplete(data) {
        if (data) {
          this.$emit('selected', data.value);
          this.text = "";
          this.selected = "";

          // Unfocus all inputText elements
          this.$nextTick(function() {
            Array.prototype.forEach.call(document.getElementsByClassName('inputText'), function(el) {
              el.blur();
            });
          });
        }
 }
```
When i do this, input has been reset and blur. But when i write again in the input, autocomplete not working and get the old autocomplete list (like a cache system) and call not working. 

### How are you importing Vue-simple-suggest?

- [ ] ESNext (original code, single-file .vue component, css included) (`import VueSimpleSuggest from 'vue-simple-suggest/lib'`)
- [X] ES6 (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] ES7 and above (`import VueSimpleSuggest from 'vue-simple-suggest/dist/es7'`)
- [ ] Bundled version (`import VueSimpleSuggest from 'vue-simple-suggest'`)
- [ ] CommonJS (`const VueSimpleSuggest = require('vue-simple-suggest')`)
- [ ] UMD Component (`<script type="text/javascript" src="https://unpkg.com/vue-simple-suggest"></script>`)

## **Please tell us about your environment:**
  - Vue.js Version: 2.5.0
  - NuxtJs Version : 1.4.0
  - Vue-simple-suggest version: 1.7.2
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

Thanks a lot for your help. 
Best regards :)

**Comment by Raiondesu** [comment] 2018-06-26 19:48
@Geminii, hmm, that's pretty interesting.
I think that the binding is not preserved after clearing the text. But I doubt the problem is that simple.
It needs deeper investigation.

For now, could you also try resetting the "text" property in Vue-Simple-Suggest and binding it again via "this.$set"?

**Comment by Geminii** [comment] 2018-06-27 11:53
Hi @Raiondesu 
I think too. 

I try to do it like this : 
```
this.text = "";
this.$set(this.$data, 'text', ''); // I create a component and use Vue-Simple-Suggest on it.
```
But not working. I try to reset "selected" property too and not working :( 
Thanks for your help :)

**Comment by Geminii** [comment] 2018-07-03 14:56
Hi @Raiondesu,
Do you reproduced this bug ? 
We need to put it in production soon, and want absolutly fix this before :) 

Thanks a lot for your help.
Regards,

**Comment by Raiondesu** [comment] 2018-08-06 10:49
After further investigation, this turned out to be a bug.
@Geminii, sorry for being silent for so long. Gonna look into this soon.

**Comment by kaskar2008** [comment] 2018-08-20 23:06
@Geminii Your solution was pretty close to an end :)
In the `$nextTick` you can just call a [clearSuggestions](https://github.com/KazanExpress/vue-simple-suggest#ref-methods) method that is described in the docs under [Ref Methods](https://github.com/KazanExpress/vue-simple-suggest#ref-methods) section. Also to provide a `blur` event you can use `$refs` for that thing. For example:
```js
this.$refs.suggestComponent.$el.querySelector('input').blur()
```
Again, sorry for being silent for so long :)
Please, close this issue if it helps.

**Comment by Raiondesu** [comment] 2018-08-22 10:35
Closing the issue for maintaining purposes.
@Geminii, reopen if the problem persists, please.

**Closed by Raiondesu** 2018-08-22 10:35 UTC
Labels: bug, help wanted, refactoring
